# Generated by Django 4.2 on 2023-04-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contant', '0002_alter_track_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='release_date',
            field=models.DateField(),
        ),
    ]
