# Generated by Django 4.2 on 2023-04-09 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contant', '0003_alter_track_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, default='к альбому не принадлежит', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='contant.album'),
        ),
    ]
