# Generated by Django 4.2 on 2023-04-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contant', '0006_remove_track_release_date_track_audio_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image',
        ),
    ]
